services:
  - type: web
    name: bot-whatsapp
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: ACCESS_TOKEN
        value: EAAapx5KgzoMBSqdX9R79aFzZBd6WPQ4YA6PUoP3343pzW7DuOc3Ft5ZARkKoGoZBKfTEnWCZBkTQF2HEUNAZAFiTUDss3pZBc9NbWjNgB5shnZBN7GSRBxTNsgZC0ZC7uhEDp6nQBdNOyLAs7VXJwAiZCuOpOYY7tIKOXJkkmuq4nThuooo7BIGiW4ZAUREKf4WOO8G3HHB0F5bl5OZAn8OR4xQYYYUlQPbY0lt1t1oKaXV31ixSdFBwZAJlXkkipFMJZBQZA6VzMOdocFwvPaViDIJXj4oC47P
      - key: PHONE_NUMBER_ID
        value: 1375650348961601
      - key: VERIFY_TOKEN
        value: 123456
