services:
  - type: web
    name: bot-whatsapp
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: ACCESS_TOKEN
        value: EAAapx5KgzoMBSsNfO4G2tI81aNgNafc77z5DLq0dZBdZAvGxGruzcEZB2TMOlY2R8ZAuExVCwOCdDzHxhPSIzKEJUTh3XMcdn6SKkvM45IygieZCE0mkavozOBYKBMvtBBvgLAhxzuIKFSRzj7NLtXZBEMICoU9g2T7sMQ8ZCBwbR7tjyioZAsIFZBIFcRuJVbZAiwEynbnRcZBWy1p8ekZAb4c009gJsOGtKb3rqxwHDGVuyYsDs0MctiWzvHNFb4GoQMl9BQ90ngxg4zt2fE8lwtU1SKOSJgZDZD
      - key: PHONE_NUMBER_ID
        value: 1375650348961601
      - key: VERIFY_TOKEN
        value: 123456
