services:
  - type: web
    name: bot-whatsapp
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: ACCESS_TOKEN
        value: EAAapx5KgzoMBSo0AnvJaK0wbWtHa2t7RzdZCfTROB5KIT79CqkuTcTZA1H2EWpCZBDECTucP1jWGytOUZBznOaOIFgPPYzLeqhHa43HArZCJCxZBkZCk7m4mWsvxBE7YAxoFASBegtu2tNTPZBGGl5L2P3T5Fs7wnEZCmqYLo8tesiWkgapeZB43ZBs1QvtD0MM7EYQxWWbZAQk4plyPO5Q5QzH4vFDvttHJYhpkCmx4PtK2pB23ZAJapaVlvmjovKuRhe8QyVvzzQ6HpMJ9ZBhZBtpSe5jaoMM
      - key: PHONE_NUMBER_ID
        value: 1375650348961601
      - key: VERIFY_TOKEN
        value: 12345
